#!/bin/bash

[[ ! -f BungeeCord.jar ]] && curl -o BungeeCord.jar https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar

java -Xmx1G -Xms512M -jar BungeeCord.jar
